"""log update4

Revision ID: 1288c7df8502
Revises: 8155ccb456f2
Create Date: 2023-08-11 02:31:19.520279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1288c7df8502'
down_revision = '8155ccb456f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'log', 'employee', ['emplyee_id'], ['id'])
    op.drop_column('log', 'employee_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'log', type_='foreignkey')
    # ### end Alembic commands ###
