"""Space and Package

Revision ID: 1cc8b0991502
Revises: 2d298e89eddb
Create Date: 2023-08-05 17:02:27.905931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1cc8b0991502'
down_revision = '2d298e89eddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('space_package')
    op.add_column('space', sa.Column('package_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'space', 'package', ['package_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'space', type_='foreignkey')
    op.drop_column('space', 'package_id')
    op.create_table('space_package',
    sa.Column('space_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('package_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], name='space_package_ibfk_1'),
    sa.ForeignKeyConstraint(['space_id'], ['space.id'], name='space_package_ibfk_2'),
    sa.PrimaryKeyConstraint('space_id', 'package_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
