"""packages2

Revision ID: 25ea6eb38896
Revises: c76e6f34a136
Create Date: 2023-08-16 02:19:09.368280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ea6eb38896'
down_revision = 'c76e6f34a136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'log', 'employee', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.drop_column('log', 'employee_id')
    # ### end Alembic commands ###
