"""PricingRule4

Revision ID: 2d298e89eddb
Revises: bf3eb381039d
Create Date: 2023-08-05 02:46:50.962818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d298e89eddb'
down_revision = 'bf3eb381039d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('space', 'area',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    op.alter_column('space', 'location',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('space', 'location',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('space', 'area',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###
