"""Space Packages3

Revision ID: 33f12728c509
Revises: d0d6cfedf0ae
Create Date: 2023-08-04 03:23:27.706425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33f12728c509'
down_revision = 'd0d6cfedf0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('log_ibfk_4', 'log', type_='foreignkey')
    op.drop_column('log', 'package_id')
    op.create_foreign_key(None, 'space', 'package', ['package_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'space', type_='foreignkey')
    op.add_column('log', sa.Column('package_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('log_ibfk_4', 'log', 'package', ['package_id'], ['id'])
    # ### end Alembic commands ###
