"""subscription_log

Revision ID: 3bb2cdcfa41f
Revises: 405a88d83e54
Create Date: 2023-09-12 02:04:16.044313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb2cdcfa41f'
down_revision = '405a88d83e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_subscription', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('use_subscription')

    # ### end Alembic commands ###
