"""subscription_customer

Revision ID: 405a88d83e54
Revises: ecd286bf37c8
Create Date: 2023-09-11 03:06:38.954225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405a88d83e54'
down_revision = 'ecd286bf37c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_startdate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_remaining', sa.Numeric(precision=4, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('subscription_remaining')
        batch_op.drop_column('subscription_startdate')

    # ### end Alembic commands ###
