"""PricingRule2

Revision ID: 691a0302c685
Revises: b6ce341797a9
Create Date: 2023-08-04 15:45:10.472861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691a0302c685'
down_revision = 'b6ce341797a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('location', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space', 'location')
    # ### end Alembic commands ###
