"""Customers Data

Revision ID: 8155ccb456f2
Revises: b1ad4ef3bf58
Create Date: 2023-08-08 00:02:05.659104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8155ccb456f2'
down_revision = 'b1ad4ef3bf58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('institute', sa.String(length=100), nullable=True))
    op.add_column('customer', sa.Column('job', sa.String(length=100), nullable=True))
    op.drop_column('customer', 'birthdate')
    op.drop_column('customer', 'national_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('national_id', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('customer', sa.Column('birthdate', sa.DATE(), nullable=True))
    op.drop_column('customer', 'job')
    op.drop_column('customer', 'institute')
    # ### end Alembic commands ###
