"""isAdmin

Revision ID: a5ea40d22d1a
Revises: 84252ce7c1e5
Create Date: 2023-08-02 16:17:41.932086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5ea40d22d1a'
down_revision = '84252ce7c1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_column('user', 'rank')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rank', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_admin')
    op.alter_column('employee', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
