"""packages-space

Revision ID: acc2774e91d7
Revises: 25ea6eb38896
Create Date: 2023-08-16 02:35:03.712183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acc2774e91d7'
down_revision = '25ea6eb38896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('package_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'log', 'package', ['package_id'], ['id'])
    op.drop_constraint('space_ibfk_1', 'space', type_='foreignkey')
    op.drop_column('space', 'package_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('package_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('space_ibfk_1', 'space', 'package', ['package_id'], ['id'])
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.drop_column('log', 'package_id')
    # ### end Alembic commands ###
