"""Pricing Less Than

Revision ID: b1ad4ef3bf58
Revises: 1cc8b0991502
Create Date: 2023-08-07 22:18:40.736094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1ad4ef3bf58'
down_revision = '1cc8b0991502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_rule', sa.Column('less_than', sa.Integer(), nullable=False))
    op.drop_column('pricing_rule', 'start_time')
    op.drop_column('pricing_rule', 'end_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_rule', sa.Column('end_time', mysql.TIME(), nullable=False))
    op.add_column('pricing_rule', sa.Column('start_time', mysql.TIME(), nullable=False))
    op.drop_column('pricing_rule', 'less_than')
    # ### end Alembic commands ###
