"""jobs3

Revision ID: b8215cabd16a
Revises: cce59558888c
Create Date: 2023-08-18 05:16:06.107626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8215cabd16a'
down_revision = 'cce59558888c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'customer', 'institute', ['institute_id'], ['id'])
    op.create_foreign_key(None, 'customer', 'job', ['job_id'], ['id'])
    op.create_foreign_key(None, 'institute', 'job', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'institute', type_='foreignkey')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    # ### end Alembic commands ###
