"""PricingRule4

Revision ID: bf3eb381039d
Revises: 691a0302c685
Create Date: 2023-08-04 16:43:15.924358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf3eb381039d'
down_revision = '691a0302c685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('space_package',
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['space.id'], ),
    sa.PrimaryKeyConstraint('space_id', 'package_id')
    )
    op.drop_constraint('package_ibfk_1', 'package', type_='foreignkey')
    op.drop_column('package', 'space_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('space_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('package_ibfk_1', 'package', 'space', ['space_id'], ['id'])
    op.drop_table('space_package')
    # ### end Alembic commands ###
