"""packages

Revision ID: c76e6f34a136
Revises: ac7b5999aab2
Create Date: 2023-08-16 02:18:31.223281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c76e6f34a136'
down_revision = 'ac7b5999aab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'emplyee_id')
    op.drop_column('log', 'employee_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('log', sa.Column('emplyee_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
