"""jobs

Revision ID: cce59558888c
Revises: acc2774e91d7
Create Date: 2023-08-18 03:41:01.613500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cce59558888c'
down_revision = 'acc2774e91d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institute',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.add_column('customer', sa.Column('job_id', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('institute_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'customer', ['institute_id'])
    op.create_unique_constraint(None, 'customer', ['job_id'])
    op.create_foreign_key(None, 'customer', 'job', ['job_id'], ['id'])
    op.create_foreign_key(None, 'customer', 'institute', ['institute_id'], ['id'])
    op.drop_column('customer', 'job')
    op.drop_column('customer', 'institute')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('institute', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('customer', sa.Column('job', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_column('customer', 'institute_id')
    op.drop_column('customer', 'job_id')
    op.drop_table('institute')
    op.drop_table('job')
    # ### end Alembic commands ###
