"""Space photo

Revision ID: d0d6cfedf0ae
Revises: 73cb44f4f599
Create Date: 2023-08-04 02:14:10.571422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d6cfedf0ae'
down_revision = '73cb44f4f599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space', 'photo')
    # ### end Alembic commands ###
